# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Fernweh的个人博客"
contentDir = "content/zh-cn"
weight = 1
    [zh-cn.params.sidebar]
        subtitle = "我的数字花园 🌱 - 基于 GitHub Pages 搭建的博客与文档。欢迎分享想法！"
    [zh-cn.menu]
        [[zh-cn.menu.main]]
            identifier = "home"
            name = "主页"
            url = "/"
            weight = 1
            [zh-cn.menu.main.params]
                icon = "home"
        [[zh-cn.menu.main]]
            identifier = "archives"
            name = "所有博客"
            url = "/archives/"
            weight = 2
            [zh-cn.menu.main.params]
                icon = "archives"
        [[zh-cn.menu.main]]
            identifier = "search"
            name = "搜索"
            url = "/search/"
            weight = 3
            [zh-cn.menu.main.params]
                icon = "search"
        [[zh-cn.menu.main]]
            identifier = "links"
            name = "链接"
            url = "/links/"
            weight = 4
            [zh-cn.menu.main.params]
                icon = "link"

[en]
languageName = "English"
languagedirection = "ltr"
title = "Personal Blogs for Fernweh"
contentDir = "content/en"
weight = 2
    [en.params.sidebar]
        subtitle = "My digital garden 🌱 - A blog and docs built with GitHub Pages. Thoughts welcome!"
    [en.menu]
        [[en.menu.main]]
            identifier = "home"
            name = "Home"
            url = "/"
            weight = 1
            [en.menu.main.params]
                icon = "home"
        [[en.menu.main]]
            identifier = "archives"
            name = "Archives"
            url = "/archives/"
            weight = 2
            [en.menu.main.params]
                icon = "archives"
        [[en.menu.main]]
            identifier = "search"
            name = "Search"
            url = "/search/"
            weight = 3
            [en.menu.main.params]
                icon = "search"
        [[en.menu.main]]
            identifier = "links"
            name = "Links"
            url = "/links/"
            weight = 4
            [en.menu.main.params]
                icon = "link"
