baseURL = 'https://blog.codeglimpse.top/demos/trip-planner/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh'
title = '远山周末｜山野周末行程'
disableKinds = ['taxonomy', 'term', 'RSS']

[markup.goldmark.renderer]
unsafe = false
